[package]
name = "pvfilt"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
tui = { version = "0.6.2", features = ["termion"] }
structopt = "0.3.4"
termion = "1.5.3"
signal-hook = "0.1.11"
regex = "1.3.1"
lazy_static = "1"
humantime = "1.3.0"
